id: authenticated
permissions:
  - 'access varbase dashboards content in drafts by user'
  - 'access varbase dashboards recent changes by user'
  - 'access varbase dashboards recently created by user'
